import { Inter } from "next/font/google";
import Head from 'next/head';
import "./globals.css";
import "@radix-ui/themes/styles.css";

const inter = Inter({ subsets: ["latin"] });

const RootLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Intro</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </>
  );
}

export default RootLayout;



